// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8afxgGqwGVDfPxmQ8lyGvUbBtmWeGQns',
    appId: '1:616162766197:web:32b44ed7f9af156a3bf73c',
    messagingSenderId: '616162766197',
    projectId: 'yamekaku-beta',
    authDomain: 'yamekaku-beta.firebaseapp.com',
    storageBucket: 'yamekaku-beta.firebasestorage.app',
    measurementId: 'G-40WNRKN5RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Bszcvf9vZPhaI1pMgkRVxFMA4I40u40',
    appId: '1:616162766197:android:a004da13502f5fad3bf73c',
    messagingSenderId: '616162766197',
    projectId: 'yamekaku-beta',
    storageBucket: 'yamekaku-beta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-iuGSGe1-Vj1Zwz0faXdXCCjqjDEELQ',
    appId: '1:616162766197:ios:d5eb7fa76eda5e863bf73c',
    messagingSenderId: '616162766197',
    projectId: 'yamekaku-beta',
    storageBucket: 'yamekaku-beta.firebasestorage.app',
    iosBundleId: 'com.example.yamekaku',
  );
}
